# Generated by Django 2.2.11 on 2020-03-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_custommodel344pm"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomModel345pm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.BigIntegerField()),
            ],
        ),
    ]
